apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config
data:
  redis.conf: |+
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file nodes.conf
    cluster-migration-barrier 1 
    appendonly yes
    protected-mode no
    dir /tmp/data
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-blue
  labels:
    app: redis
    member: redis-blue
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        member: redis-blue
    spec:
      hostNetwork: true
      containers:
      - name: redis
        image: kub01.news.bjyt.qihoo.net:5000/redis_c:latest
        command: ["/bin/sh", "-c"]
        args: ["/usr/local/bin/redis-server /conf/redis.conf"]
        ports:
        - containerPort: 6379
          name: redis-port
        - containerPort: 16379
          name: cluster-port
        volumeMounts:
        - mountPath: /tmp/data
          name: data
        - name: conf
          mountPath: /conf
          readOnly: false
      volumes:
      - name: data
        hostPath:
          path: /tmp/redis-blue
      - name: conf
        configMap:
          name: redis-cluster-config
          items: 
          - key: redis.conf
            path: redis.conf
