apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-claim-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

  selector:
    matchLabels:
      usefor: test
    #matchExpressions:
    #  - {key: environment, operator: In, values: [dev]}
