apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: kube-system
type: "kubernetes.io/rbd"  
data:
  #key: AQBUpGRZ9fg+CBAAmqbnLT6sEwOUM+bKaQs0cQ==
  key: QVFCVXBHUlo5ZmcrQ0JBQW1xYm5MVDZzRXdPVU0rYkthUXMwY1E9PQo=
